<a href="https://colab.research.google.com/github/siusta/wstep-do-ml-Siusta-175ic/blob/main/zad3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python basics**

In [ ]:
#1 Tworzenie listy
list = [[9,8,7,6],[5,4,3,2]]
list

[[9, 8, 7, 6], [5, 4, 3, 2]]

In [ ]:
#2 Wybranie podlisty o indeksie 0
list[0]

[9, 8, 7, 6]

In [ ]:
#3 Usunięcie ostatniego elementu
list.pop(-1)

[5, 4, 3, 2]

In [ ]:
#4 Dodanie elementu do listy
list.append('extra')
list

[[9, 8, 7, 6], 'extra']

In [ ]:
#5 Odwrócenie listy
list.reverse()
list

['extra', [9, 8, 7, 6]]

**NumPy Basics**

In [ ]:
import numpy as np
a = np.random.randint(100, size=(3,4))

In [ ]:
#1 Suma elementów tablicy
a.sum()

667

In [ ]:
#2 Sortowanie tablicy
a.sort()
a

array([[41, 44, 70, 92],
       [19, 20, 87, 94],
       [ 4, 57, 67, 72]])

In [ ]:
#3 Transponowanie tablicy
b = a.T
b

array([[41, 19,  4],
       [44, 20, 57],
       [70, 87, 67],
       [92, 94, 72]])

In [ ]:
#4 Mnożenie tablicy a i b
a.dot(b)

array([[16981, 16397, 13986],
       [16397, 17166, 13813],
       [13986, 13813, 12938]])

In [39]:
#5 Wypisanie elementów tablicy, które są mniejsze od 40
a[a<60]

array([41, 44, 19, 20,  4, 57])

**SciPy - Linear Algebra**

In [40]:
from scipy import linalg

In [43]:
#1 Stworzenie macierzy randomowych wartości z zakresu (0,40)
A = np.mat(np.random.randint(40,size = (4,4)))
A

matrix([[34, 33, 28, 25],
        [ 5, 32, 13, 39],
        [36, 34, 26,  0],
        [13,  6,  1, 25]])

In [44]:
#2 Stworzenie macierzy odwrotnej do A
A.I

matrix([[-0.01998079, -0.02161383,  0.03025937,  0.05369837],
        [-0.08096382,  0.04262728,  0.06532181,  0.01446526],
        [ 0.13354147, -0.02581652, -0.08885687, -0.09326769],
        [ 0.02447967,  0.00204131, -0.02785783,  0.01233589]])

In [45]:
#3 Stworzenie macierzy jednostkowej
B = np.eye(4,k=0)
B

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
#4 Sinus macierzy A
linalg.sinm(A)

array([[   69.82114586,    85.77108118,   709.4854262 , -2685.01461394],
       [ -310.81658798,   176.9608659 ,  -894.79433915,  3631.55972931],
       [ -418.81643248,   848.62006593,  1263.35434855, -4186.73293523],
       [  521.95793124,  -778.2439185 ,  -445.46361807,  1065.71133829]])

In [51]:
#5 Dodawanie macierzy
np.add(A,B)

matrix([[35., 33., 28., 25.],
        [ 5., 33., 13., 39.],
        [36., 34., 27.,  0.],
        [13.,  6.,  1., 26.]])

**Pandas Basics**

In [75]:
import pandas as pd
import io

In [76]:
from google.colab import files
uploaded = files.upload()

Saving ramen-ratings.csv to ramen-ratings.csv


In [78]:
df = pd.read_csv(io.StringIO(uploaded['ramen-ratings.csv'].decode('utf-8')))
ramen= df.copy()
df

Review #           Brand  ... Stars Top Ten
0         2580       New Touch  ...  3.75     NaN
1         2579        Just Way  ...     1     NaN
2         2578          Nissin  ...  2.25     NaN
3         2577         Wei Lih  ...  2.75     NaN
4         2576  Ching's Secret  ...  3.75     NaN
...        ...             ...  ...   ...     ...
2575         5           Vifon  ...   3.5     NaN
2576         4         Wai Wai  ...     1     NaN
2577         3         Wai Wai  ...     2     NaN
2578         2         Wai Wai  ...     2     NaN
2579         1        Westbrae  ...   0.5     NaN

[2580 rows x 7 columns]

In [105]:
#1 Informacje o DataFrame
ramen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2580 entries, 0 to 2579
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Review #  2580 non-null   int64 
 1   Brand     2580 non-null   object
 2   Variety   2580 non-null   object
 3   Style     2578 non-null   object
 4   Country   2580 non-null   object
 5   Stars     2580 non-null   object
 6   Top Ten   41 non-null     object
dtypes: int64(1), object(6)
memory usage: 141.2+ KB


In [102]:
#2 Sortowanie wg "Stars" 
ramen.sort_values('Stars',ascending=False)

Review #           Brand  ...    Stars Top Ten
122       2458   Samyang Foods  ...  Unrated     NaN
993       1587        Mi E-Zee  ...  Unrated     NaN
32        2548          Ottogi  ...  Unrated     NaN
447       2133          Nissin  ...     5.00     NaN
454       2126          Nissin  ...     5.00     NaN
...        ...             ...  ...      ...     ...
524       2056            Koyo  ...        0     NaN
563       2017   Samyang Foods  ...        0     NaN
952       1628           Azami  ...        0     NaN
2082       498  Hsin Tung Yang  ...        0     NaN
53        2527   Uni-President  ...        0     NaN

[2580 rows x 7 columns]

In [100]:
#3 Sortowanie boolowskie (taiwan - true)
taiwan = ramen[ramen.Country=='Taiwan']
taiwan

Review #             Brand  ... Stars Top Ten
1         2579          Just Way  ...     1     NaN
3         2577           Wei Lih  ...  2.75     NaN
40        2540           Wei Lih  ...  3.25     NaN
65        2515     Uni-President  ...     5     NaN
68        2512  Mom's Dry Noodle  ...     5     NaN
...        ...               ...  ...   ...     ...
2500        80     Unif / Tung-I  ...   3.5     NaN
2512        68           Wei Lih  ...     4     NaN
2522        58           Ve Wong  ...     3     NaN
2537        43       Kim Ve Wong  ...     0     NaN
2572         8            Tung-I  ...     3     NaN

[224 rows x 7 columns]

In [109]:
#4 Wartość mediany ocen firmy vifon 
vifon = ramen[ramen.Brand=='Vifon']
vifon.Stars.median()

3.25

In [110]:
#5 Usunięcie kolumnt Top Ten
ramen.drop('Top Ten',axis=1)

Review #           Brand  ...   Country Stars
0         2580       New Touch  ...     Japan  3.75
1         2579        Just Way  ...    Taiwan     1
2         2578          Nissin  ...       USA  2.25
3         2577         Wei Lih  ...    Taiwan  2.75
4         2576  Ching's Secret  ...     India  3.75
...        ...             ...  ...       ...   ...
2575         5           Vifon  ...   Vietnam   3.5
2576         4         Wai Wai  ...  Thailand     1
2577         3         Wai Wai  ...  Thailand     2
2578         2         Wai Wai  ...  Thailand     2
2579         1        Westbrae  ...       USA   0.5

[2580 rows x 6 columns]

**Scikit-learn**